CREATE TABLE IF NOT EXISTS pois (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    name_en VARCHAR(255),
    category VARCHAR(50) NOT NULL,
    subcategory VARCHAR(50),
    address TEXT,
    city VARCHAR(100),
    phone VARCHAR(20),
    website VARCHAR(500),
    opening_hours JSONB,
    rating DECIMAL(2,1) DEFAULT 0,
    review_count INTEGER DEFAULT 0,
    price_level INTEGER DEFAULT 2,
    has_wifi BOOLEAN DEFAULT FALSE,
    has_outlets BOOLEAN DEFAULT FALSE,
    has_terrace BOOLEAN DEFAULT FALSE,
    has_parking BOOLEAN DEFAULT FALSE,
    has_live_music BOOLEAN DEFAULT FALSE,
    has_breakfast BOOLEAN DEFAULT FALSE,
    is_quiet BOOLEAN DEFAULT FALSE,
    is_family_friendly BOOLEAN DEFAULT FALSE,
    is_romantic BOOLEAN DEFAULT FALSE,
    is_dog_friendly BOOLEAN DEFAULT FALSE,
    noise_level VARCHAR(10) DEFAULT 'medium',
    osm_id BIGINT UNIQUE,
    osm_type VARCHAR(10),
    source VARCHAR(50) DEFAULT 'osm',
    last_updated TIMESTAMP DEFAULT NOW(),
    geom GEOGRAPHY(POINT, 4326) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);
